#!/bin/bash

git clone https://github.com/MD2Korg/mCerebrum
git clone https://github.com/MD2Korg/mCerebrum-EMA
git clone https://github.com/MD2Korg/mCerebrum-DataKit
git clone https://github.com/MD2Korg/mCerebrum-AutoSense
git clone https://github.com/MD2Korg/mCerebrum-DataKitAPI
git clone https://github.com/MD2Korg/mCerebrum-Study
git clone https://github.com/MD2Korg/mCerebrum-PhoneSensor
git clone https://github.com/MD2Korg/mCerebrum-DemoApp
git clone https://github.com/MD2Korg/mCerebrum-ThoughtShakeup
git clone https://github.com/MD2Korg/mCerebrum-Utilities
git clone https://github.com/MD2Korg/mCerebrum-StreamProcessor
git clone https://github.com/MD2Korg/mCerebrum-MoodSurfing
git clone https://github.com/MD2Korg/mCerebrum-NotificationManager
git clone https://github.com/MD2Korg/mCerebrum-OralB
git clone https://github.com/MD2Korg/mCerebrum-EMAScheduler
git clone https://github.com/MD2Korg/mCerebrum-Plotter
git clone https://github.com/MD2Korg/mCerebrum-EasySense
git clone https://github.com/MD2Korg/mCerebrum-SelfReport
git clone https://github.com/MD2Korg/mCerebrum-MotionSense
git clone https://github.com/MD2Korg/mCerebrum-Configuration
git clone https://github.com/MD2Korg/mCerebrum-MicrosoftBand
git clone https://github.com/MD2Korg/mCerebrum-docs
git clone https://github.com/MD2Korg/mCerebrum-Medication
git clone https://github.com/MD2Korg/mCerebrum-StudymPerf
git clone https://github.com/MD2Korg/mCerebrum-Scheduler
git clone https://github.com/MD2Korg/mCerebrum-SOBCLab
git clone https://github.com/MD2Korg/mCerebrum-Omron
git clone https://github.com/MD2Korg/mCerebrum-MindfulnessStrategy
git clone https://github.com/MD2Korg/mCerebrum-CHFScheduler
git clone https://github.com/MD2Korg/mCerebrum-Beacon
git clone https://github.com/MD2Korg/mCerebrum-Library
git clone https://github.com/MD2Korg/mCerebrum-AutoSenseBLE
git clone https://github.com/MD2Korg/mCerebrum-StudymPerfLab
git clone https://github.com/MD2Korg/mCerebrum-StudyDataCollection
git clone https://github.com/MD2Korg/mCerebrum-StudyWithEMA
